### PR TITLE
Honor DESTDIR variable in install target

### PR DESCRIPTION
**Pull request by glondu**

### CODE REVIEW

**Comment by gasche** [comment]
This looks good to me, with a minor nit: `DESTDIR` is used in the Makefile now but never defined. In OCaml we at some point added https://github.com/ocaml/ocaml/commit/4b6174d624c329872fcb19ab1704eaa81dd7162f to use `DESTDIR ?=` to give it an empty default value, which avoids warnings when `--warn-undefined-variables` is used.

**Comment by dra27** [comment]
Please could the `uninstall` target be updated too, FWIW

**Comment by glondu** [comment]
> `DESTDIR` is used in the Makefile now but never defined

> Please could the `uninstall` target be updated too, FWIW

Done.

**Comment by dra27** [comment]
It should be `DESTDIR`, not `PREFIX`, shouldn't it?

**Comment by glondu** [comment]
> It should be `DESTDIR`, not `PREFIX`, shouldn't it?

Right. Sorry for the noise.

**Comment by dra27** [comment]
No worries - thanks for the patch!

**Pull request merged**
