### PR TITLE
Remove warnings with OCaml 4.13

### PR DESCRIPTION
**Pull request by kit-ty-kate**
In prevision of https://github.com/ocaml/ocaml/pull/10207

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Now that https://github.com/ocaml/ocaml/pull/10207 is merged this PR is good to go.

**Comment by dra27** [comment]
Please could you update the `Makefile`s as well?

https://github.com/ocaml/num/blob/5698bc491dd3f9f8c92e97da7ffc8d984a5e90da/src/Makefile#L21

and

https://github.com/ocaml/num/blob/5698bc491dd3f9f8c92e97da7ffc8d984a5e90da/toplevel/Makefile#L6

**Comment by kit-ty-kate** [comment]
Done

**Comment by dra27** [comment]
There is a question over whether `-warn-error A` will definitely trigger the alert, but the change is benign as things stand. I'll merge: if num 1.4 still triggers the warning when 4.13 is branched then we'll know we need to release.

**Pull request merged**
